 ► AI Chatbots

*     ⭐⭐⭐ [ChatGPT](https://chat.openai.com/) - GPT Based Chatbot
*     ⭐⭐ [OpenAI Playground](https://platform.openai.com/playground) - GPT-3 / GPT 3.5 / GPT-4 including 4 interaction modes
*     ⭐⭐ [Bard](https://bard.google.com/) - Google's Chatbot
*     ⭐ [Phind](https://www.phind.com/) - GPT-4 Dev Q&A AI / [Discord](https://discord.com/invite/S25yW8TebZ) / [GPT-4 Note](https://pastebin.com/JJMVmUCN)
*     ⭐ [Perplexity](https://www.perplexity.ai/) or [FastGPT](https://labs.kagi.com/fastgpt) - GPT-3.5 Q&A AI / [Discord](https://discord.com/invite/perplexity-ai)
*     ⭐ [Text Generation WebUI](https://github.com/oobabooga/text-generation-webui) - Self-Host Open Source LLMs / [Collab](https://colab.research.google.com/github/pcrii/Philo-Colab-Collection/blob/main/4bit_TextGen_Gdrive.ipynb)
*     ⭐ [llama.cpp](https://github.com/ggerganov/llama.cpp) or [ChatLLaMA](https://stuff.serp.ai/l/lora-weights) - Self-Host LLaMa Based Chatbots
*     ⭐ [Guanaco](https://huggingface.co/spaces/uwnlp/guanaco-playground-tgi) - QLoRA based Open-Source Chatbot / [Github](https://github.com/artidoro/qlora)
*     ⭐ [BAI](https://chatbot.theb.ai/) - GPT-3.5 Based Chatbot
*     ⭐ [LMSYS](https://chat.lmsys.org/) - LLaMa Based Chatbots / [Github](https://github.com/lm-sys/FastChat) / [Discord](https://discord.com/invite/h6kCZb72G7)
*     ⭐ [AI Playground](https://play.vercel.ai/) - Compare AI Responses
*     
*     ⭐ [Call Annie](https://callannie.ai/) - Virtual Companion / [Discord](https://discord.gg/Rfbzet5R3v)
*     ⭐ [Character AI](https://beta.character.ai/) - Roleplaying Chatbots / [Extract Params](https://rentry.org/reverseCAI)
*     ⭐ [LifeArchitect](https://lifearchitect.ai/models-table/) or [Awesome Totally Open ChatGPT](https://github.com/nichtdax/awesome-totally-open-chatgpt) - Chatbots Indexes
*     [Ora](https://ora.sh/openai/chatgpt) - GPT-3.5 Based Chatbots
*     [bing-chat](https://github.com/transitive-bullshit/bing-chat) - Bing's Chatbot / [API](https://github.com/acheong08/EdgeGPT)
*     [LLaVA](https://llava.hliu.cc/) - Chatbot with Image Support / [GitHub](https://github.com/haotian-liu/LLaVA)
*     [MPT-7B-Chat](https://huggingface.co/spaces/mosaicml/mpt-7b-chat) - Mosaic's Open-Source Chatbot / [Instruct](https://huggingface.co/spaces/mosaicml/mpt-7b-instruct) / [Storywriter](https://huggingface.co/spaces/mosaicml/mpt-7b-storywriter)
*     [ChatRWKV](https://huggingface.co/spaces/BlinkDL/ChatRWKV-gradio) - RWKV Based Chatbot / [7B Version](https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B) / [Discord](https://discord.com/invite/bDSBUMeFpc)
*     [GPT4All](https://github.com/nomic-ai/gpt4all) - Open-Source Chatbot / [Discord](https://discord.com/invite/mGZE39AS3e)
*     [Open Assistant](https://open-assistant.io/) - Open-Source Chatbot / [Github](https://github.com/LAION-AI/Open-Assistant) / [Discord](https://discord.com/invite/H769HxZyb5)
*     [StableLM](https://colab.research.google.com/github/Stability-AI/StableLM/blob/main/notebooks/stablelm-alpha.ipynb) - Open-Source Chatbot / [Github](https://github.com/stability-AI/stableLM/)
*     [OpenChatKit](https://huggingface.co/spaces/togethercomputer/OpenChatKit) - Open-Source Chatbot / [Github](https://github.com/togethercomputer/OpenChatKit) / [Discord](https://discord.com/invite/9Rk6sSeWEG)
*     [HuggingChat](https://huggingface.co/chat/) - HuggingFace's Chatbot / [Github](https://github.com/huggingface/chat-ui)
*     [Dalai](https://cocktailpeanut.github.io/dalai/) - Self-host LLaMa and Alpaca Chatbots / [Github](https://github.com/cocktailpeanut/dalai) / [Discord](https://discord.com/invite/WWfgrzzkCT) / [GPT-Style UI](https://github.com/ItsPi3141/dalai)
*     [Alpaca](https://github.com/tatsu-lab/stanford_alpaca) - Stanford's Chatbot / [LoRA Implementation](https://github.com/tloen/alpaca-lora) / [GUI](https://github.com/ItsPi3141/alpaca-electron)
*     [FreedomGPT](https://freedomgpt.com/) - Self-Hosted Alpaca Based Chatbot / [Github](https://github.com/ohmplatform/FreedomGPT/) / [Discord](https://discord.com/invite/h77wvJS4ga)
*     [PygmalionAI](https://docs.alpindale.dev/) - Self-Hosted Roleplaying Chatbot / [Resources](https://rentry.co/PygmalionLinks) / [Discord](https://discord.com/invite/pygmalionai)
*     [chat-llm-streaming](https://huggingface.co/spaces/olivierdehaene/chat-llm-streaming) - Multiple Chatbots
*     [DeepAI](https://deepai.org/chat) - DeepAI's Chatbot
*     [Ethio Tech](https://gpt3.ethio-tech.com/) - GPT-3 Based Chatbot
*     [JackChat](https://www.jackchat.ai/) - GPT-3 Based Chatbot
*     [Leon](https://getleon.ai/) - AI Assistant
*     [AnimaAI](https://myanima.ai/) - Virtual Companion
*     [Forefront](https://chat.forefront.ai/) - Roleplaying Chatbots
*     [hellohistory](https://www.hellohistory.ai/) - Historical Roleplaying Chatbot
*     [Chai](https://www.chai-research.com/) or [MessengerX](https://www.messengerx.io/) - Entertainment Focused Chatbots
*     [CatGPT](https://cat-gpt.com/) - Cat Chatbot
*     [CharacterHub](https://www.characterhub.org/) - Characters for LLMs
*     [AI Anything](https://aianything.netlify.app/) - Create Chatbots
*     [Alt-GPT](https://github.com/Feedox/alt-gpt) - Create GPT Plugins
*     [Auto-GPT](https://github.com/Significant-Gravitas/Auto-GPT) - Autonomous GPT-4 / [GUI](https://github.com/thecookingsenpai/autogpt-gui)
*     [MiniAGI](https://github.com/muellerberndt/mini-agi) - Autonomous GPT-3.5 / GPT-4
*     [Kajiwoto](https://kajiwoto.com/), [Miku](https://docs.miku.gg/) / [Discord](https://discord.gg/3XPdpUdGgV) or [Agnai](https://agnai.chat/) - AI Builders
*     [SillyTavern](https://github.com/Cohee1207/SillyTavern) - UI for Roleplaying Chatbots

 ► ChatGPT Tools

*     ⭐ [Awesome ChatGPT](https://github.com/humanloop/awesome-chatgpt), [GPT Resources](https://airtable.com/shrWat9yoXFwOXWQ0/tblxXHpcpjn1POWnh), [WikiGPT3](https://www.wikigpt3.com/), [Awesome-GPT4](https://github.com/radi-cho/awesome-gpt4) or [SaaS GPTers](https://saasgpters.com/) - ChatGPT Resources
*     ⭐⭐ [SuperPower ChatGPT](https://addons.mozilla.org/en-US/firefox/addon/superpower-chatgpt/) / [2](https://chrome.google.com/webstore/detail/superpower-for-chatgpt/amhmeenmapldpjdedekalnfifgnpfnkc) or [Merlin](https://merlin.foyer.work/) - Enhancement Extensions
*     ⭐ [FOFA](https://en.fofa.info/result?qbase64=ImxvYWRpbmctd3JhcCIgJiYgImJhbGxzIiAmJiAiY2hhdCIgJiYgaXNfZG9tYWluPXRydWU%3D) / [2](https://en.fofa.info/result?qbase64=dGl0bGU9PSJDaGF0R1BUIFdlYiI%3D) - Find No-Login Frontends
*     ⭐ [/r/ChatGPT](https://www.reddit.com/r/ChatGPT/) - ChatGPT Subreddit
*     ⭐ [ChatPDF](https://www.chatpdf.com/) or [Humata](https://www.humata.ai/) - Turn Files into Chatbots
*     [EmergentMind](https://www.emergentmind.com/) - AI News
*     [ChatWebpage](https://chatwebpage.com/) - Turn Webpages into Chatbots
*     [ChatBlade](https://github.com/npiv/chatblade) - ChatGPT CLI
*     [engshell](https://github.com/emcf/engshell) or [TGPT](https://github.com/aandrew-me/tgpt) - ChatGPT in TUIs
*     [FreeGPT](https://freegpt.one/), [ChatGPTClone](https://github.com/xtekky/chatgpt-clone), [YakGPT](https://yakgpt.vercel.app/) or [TurboGPT.ai](https://turbogpt.ai/) - AI Chat WebUIs
*     [ChatGPT Desktop](https://github.com/sonnylazuardi/chat-ai-desktop), [TurboGPT](https://github.com/mikebpech/turbogpt.ai) or [lencx](https://github.com/lencx/ChatGPT/) - Desktop Apps
*     [AICommand](https://github.com/keijiro/AICommand) - ChatGPT for Unity Editor
*     [docGPT](https://github.com/cesarhuret/docGPT) - ChatGPT Google Docs Addon
*     [ChatHub](https://chathub.gg/) or [ChatGPTBox](https://github.com/josStorer/chatGPTBox) - ChatGPT Browser Extensions
*     [chatgpt-discord-bot](https://github.com/TuringAI-Team/chatgpt-discord-bot), [CharacterAI](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot) or [chatGPT-discord-bot](https://github.com/Zero6992/chatGPT-discord-bot) - ChatGPT for Discord
*     [ChatGPT Telegram Bot](https://github.com/karfly/chatgpt_telegram_bot) / [2](https://github.com/n3d1117/chatgpt-telegram-bot) / [3](https://github.com/watscho/chat-gpt-telegram-bot) or [chatgpt-telegram-bot-serverless](https://github.com/franalgaba/chatgpt-telegram-bot-serverless) - ChatGPT for Telegram
*     [WeChat ChatGPT](https://github.com/fuergaosi233/wechat-chatgpt) - ChatGPT for WeChat
*     [ChatGPTSlackBot](https://github.com/pedrorito/ChatGPTSlackBot) - ChatGPT for Slack
*     [ChatGPT Advanced](https://tools.zmo.ai/webchatgpt) - Add Search Results to ChatGPT / [Discord](https://discord.com/invite/pkZ3wwuT)
*     [ChatGPT4Google](https://chatgpt4google.com/), [SublimeGPT](https://chrome.google.com/webstore/detail/sublimegpt-chatgpt-everyw/eecockeebhenbihmkaamjlgoehkngjea) or [GPTGO](https://gptgo.ai/) - Add ChatGPT to Search Results
*     [Andi](https://andisearch.com/) - AI Powered Search
*     [ShareGPT](https://sharegpt.com/) or [ChatGPT Exporter](https://greasyfork.org/en/scripts/456055) - Export Chats
*     [ChatGPT Notification](https://github.com/Correia-jpv/ChatGPT-Notification) - Receive Notifications
*     [Autoclear ChatGPT History](https://github.com/adamlui/userscripts/tree/master/chatgpt/autoclear-chatgpt-history) - Autoclear Chats
*     [EditGPT](https://www.editgpt.app/) - Proofread Chats
*     [RepeatGPT](https://repeatgpt.com/) - Schedule Chats
*     [ChatGPT-Matrix-Style](https://github.com/lvwzhen/ChatGPT-Matrix-Style) - Matrix Theme
*     [openai_pipe](https://github.com/Aesthetikx/openai_pipe) - Unix Theme

 ► ChatGPT Prompts

*     ⭐ [Awesome ChatGPT Prompts](https://prompts.chat/) / [2](https://github.com/f/awesome-chatgpt-prompts) - Prompt Directory
*     ⭐ [Prompt Engineering Guide](https://www.promptingguide.ai/) or [Learn Prompting](https://learnprompting.org/) - Prompting Guides
*     ⭐ [quickref](https://quickref.me/chatgpt) - Prompt Cheatsheet
*     ⭐ [jailbreakchat](https://www.jailbreakchat.com/), [jamessawyer](http://www.jamessawyer.co.uk/pub/gpt_jb.html) or [DAN](https://gist.github.com/coolaj86/6f4f7b30129b0251f61fa7baaa881516)- Jailbreak Prompts
*     [Chatgptjailbreak](https://rentry.org/Chatgptjailbreak) - Prompt Directory
*     [500 Best Prompts](https://puzzle-jute-202.notion.site/500-Best-ChatGPT-Prompts-f5b4ad65deec4b6385316fdb8740af74) - Prompt Directory
*     [flowgpt](https://flowgpt.com/) - Prompt Directory
*     [Prompts Hub](https://docs.google.com/spreadsheets/d/1Y-xQwFkQFCKhPB3nOMyTMNPZ-vaFiof2-vWGBAeupTo/edit#gid=0) - Prompt Directory
*     [DataFit](https://datafit.ai/top-chatgpt-prompts) - Prompt Directory
*     [OrdinaryPeoplePrompts](https://www.ordinarypeopleprompts.com/) - Prompt Directory
*     [SD Dynamic Prompts](https://github.com/adieyal/sd-dynamic-prompts) or [PromptBot](https://www.messengerx.io/promptbot) - Prompt Generators
*     [PromptPerfect](https://promptperfect.jina.ai/) - Pro**mpt Optimizer
*     [botprompts](https://botprompts.net/) - Fun Prompts
*     [ChatGPT-History](https://github.com/benf2004/ChatGPT-Prompt-Genius) - Prompt Management Extensions
*     [/r/ChatGPTJailbreak](https://www.reddit.com/r/ChatGPTJailbreak/) or [/r/GPT_Jailbreaks](https://www.reddit.com/r/GPT_jailbreaks/) - GPT Jailbreak Subreddits

  ► AI Indexes

*     ⭐ [Futurepedia](https://www.futurepedia.io/) - AI Directory
*     ⭐ [AI-MF](https://whoisdsmith.gitbook.io/ai-mf/) - AI Directory / [GitHub](https://github.com/whoisdsmith/AI-MTHRFCKR)
*     ⭐ [AIcyclopedia](https://www.aicyclopedia.com/) - AI Directory
*     ⭐ [A.I. Apps](https://appraven.net/collection.php?listId=63b5eef1904afd2a981cead0) - AI iOS App Directory
*     [Awesome Artificial Intelligence](https://github.com/owainlewis/awesome-artificial-intelligence#free-content) - AI Resources / Learning
*     [Favird](https://favird.com/) - AI Directory
*     [FutureTools](https://www.futuretools.io/?pricing-model=free) - AI Directory
*     [ToolScoutAI](https://toolscout.ai/) - AI Directory
*     [AI Creator Tools](https://library.phygital.plus/) - AI Directory
*     [topai](https://topai.tools/) - AI Directory
*     [TheresAnAIForThat](https://theresanaiforthat.com/) - AI Directory
*     [AI-Infinity](https://aiinfinity-meetpatel.notion.site/AI-Infinity-AI-Tools-Directory-0da673c487124ea2b6f8ebe59b75a231) - AI Directory
*     [AI Center](https://aicenter.ai/) - AI Directory
*     [Wiki AI Tools](https://www.wikiaitools.com/) - AI Directory
*     [TopApps.Ai](https://topapps.ai/) - AI Directory
*     [Cookup AI](https://cookup.ai/) - AI Directory
*     [SuperTools](https://supertools.therundown.ai/) - AI Directory
*     [iLib](https://www.ilib.com/) - AI Directory
*     [ArtificialStudio](https://www.artificialstudio.ai/tools) - Browser Based AI
*     [RunwayML](https://runwayml.com/) - Browser Based AI
*     [Experiments with Google](https://labs.withgoogle.com/) - AI Experiments
*     [OpenCV](https://opencv.org/) - A.I. Vision Library
*     [OpenCog](https://opencog.org/) or [AForge](https://github.com/andrewkirillov/AForge.NET) - Artificial Intelligence Frameworks
*     [free-ai-resources](https://github.com/mrsaeeddev/free-ai-resources) - AI Learning Resources
*     [AI Reading List](https://docs.google.com/document/d/1bEQM1W-1fzSVWNbS4ne5PopB2b7j8zD4Jc3nm4rbK-U/) - AI Research Papers

  ► LLM AI's Text Generators

*     ⭐ [ChatGPT](https://chat.openai.com/) - GPT-3 Based AI
*     ⭐ [Bard](https://bard.google.com/) - Google's AI
*     ⭐ [Poe](https://poe.com/) - GPT-3.5 Based AI
*     ⭐ [Ora](https://ora.sh/openai/chatgpt) - GPT-3.5 Based AI
*     [BAI](https://chatbot.theb.ai/) - GPT-3.5 Based AI
*     [LangChain](https://huggingface.co/spaces/JavaFXpert/Chat-GPT-LangChain) - GPT-3.5 Based AI
*     [gpt3](https://gpt3.ethio-tech.com/) - GPT-3 Based AI
*     [Transformer](https://transformer.huggingface.co/) - GPT-2 Based AI
*     [bing-chat](https://github.com/transitive-bullshit/bing-chat) - Bing's Text AI / [API](https://github.com/acheong08/EdgeGPT)
*     [Cognosys](https://www.cognosys.ai/) - Task-Specific AI Text Generators
*     [NovelAI](https://novelai.net/) / [2](https://rentry.org/sdg_FAQ) - Story Writing AI / [Limit Bypass](https://pastebin.com/JDyvqZcz)
*     [KoboldAI](https://github.com/KoboldAI/KoboldAI-Client) / [2](https://github.com/henk717/KoboldAI) - Story Writing AI / [GGML Models](https://github.com/LostRuins/koboldcpp) / [Web App](https://lite.koboldai.net/)
*     [Dreamily](https://dreamily.ai/) - Story Writing AI
*     [Unconventional Text Writer](https://unconventional-text-writer.netlify.app/) - Unconventional Text AI
*     [Character Creator](https://oobabooga.github.io/character-creator) - Character Generation AI
*     [GPTForSlides](https://www.gptforslides.app/) or [Chat-GPT-PPT](https://github.com/williamfzc/chat-gpt-ppt) - Presentation AIs
*     [Essaytyper](http://www.essaytyper.com/) - Essay Writing AI
*     [papertyper](https://papertyper.net/) - Essay Writing AI
*     [EssayBot](https://www.essaybot.com/) / [2](https://www.essayaibot.com/) - Essay Writing AI
*     [PerfectEssayWriter](https://www.perfectessaywriter.ai/) - Essay Writing AI
*     [Chat GPTPhantom](https://chatgpt-phantom.vercel.app/) - Article Writing AI
*     [Marmof](https://marmof.com/) - Creator / Marketing AI
*     [GPT4Chat](https://gpt4chat.net/) or [ChatGPT Writer](https://chatgptwriter.ai/) - Email Reply AI
*     [codex-readme](https://github.com/tom-doerr/codex-readme) - README AI Generator
*     [WTFDoesThisCompanyDo](https://wtfdoesthiscompanydo.vercel.app/) or [SiteExplainer](https://www.siteexplainer.com/) - AI Site Explanations
*     [EleutherAI](https://6b.eleuther.ai/) - Text Autocomplete AI
*     [Talk to Transformer](https://app.inferkit.com/demo) - Text Autocomplete AI
*     [TextSynth](https://textsynth.com/playground.html) - Text Autocomplete AI
*     [Basaran](https://github.com/hyperonym/basaran) - Text Autocomplete AI
*     [Compose](https://www.compose.ai/) - Text Autocomplete AI Extension
*     [InkForAll](https://app.inkforall.com/tools) - Multiple AI Text Tools
*     [SheetPlus](https://sheetplus.ai/), [NumerousAI](https://workspace.google.com/marketplace/app/numerousai/575253125118) or [FormulaBot](https://formulabot.com/) - Excel AI Tools
*     [GPT-JT](https://huggingface.co/togethercomputer/GPT-JT-6B-v1) - Text Classification AI
*     [Image2Paragraph](https://github.com/showlab/Image2Paragraph) - Image to Descriptive Paragraph
*     [Auto Text Expander](https://pastebin.com/TFPRieVN) - Shortcuts to Expand & Replace Text as you Type